# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NodesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exec_time', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.FilePathField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config_app.NodesGroup'),
        ),
    ]
